name: Enforce Conventional Commits Before Merge

on:
  pull_request:
    # types of PR events to trigger checks
    types: [opened, reopened, edited, synchronize]

jobs:
  enforce-conventional-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get the latest commit message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%s)
          echo "Last commit message: $COMMIT_MSG"
          if [[ ! "$COMMIT_MSG" =~ ^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert|BREAKING CHANGE)(\(.+\))?:\  ]]; then
            echo "❌ Commit message does not follow Conventional Commit format!"
            exit 1
          fi
