name: Enforce Conventional Commits Before Merge

on:
  pull_request:
    # types of PR events to trigger checks
    types: [opened, reopened, edited, synchronize]

jobs:
  enforce-conventional-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
