name: Enforce Conventional Commits on Squash & Merge

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed  # Still needed for post-merge validation

jobs:
  validate-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: echo "PR was merged."

      - name: Validate Commit Message
        if: github.event.pull_request.merged == true
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:%s)
          echo "Last commit message: $COMMIT_MSG"
          if [[ ! "$COMMIT_MSG" =~ ^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert|BREAKING CHANGE)(\(.+\))?:\  ]]; then
            echo "❌ Commit message does not follow Conventional Commit format!"
            exit 1
          fi
