name: Enforce Conventional Commits Before Merge

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  validate-final-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
